# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
    branches:
      include:
      - '*'
    paths:
      exclude:
      - CHANGELOG.md

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - checkout: self
    clean: true
    persistCredentials: true

  - task: Bash@3
    name: Release
    env:
      STAGING_PATH: $(Build.ArtifactStagingDirectory)
      LOCAL_PATH: $(Build.Repository.LocalPath)
      DOCKER_HUB_PASSWORD: $(DOCKER_HUB_PASSWORD)
    inputs:
      targetType: 'inline'
      script: |
        #npm install    ### instead unpack readymade semantic-release archive (much faster)
        time curl -L https://github.com/Elders/blob/releases/download/SemRel-01/node_modules.tar.gz | tar mx -I pigz
        time npx semantic-release --no-ci
